version: '3.8'

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpassword
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    volumes:
      - redis-data:/redis
    ports:
      - "5379:5379"

  server:
    build:
      context: .
      dockerfile: apps/server/server
    environment:
      - PORT=4000
      - BASE_URL=http://localhost:3000
      - REDIS_URL=redis://redis:6379
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis

  nextjs:
    build:
      context: .
      dockerfile: apps/nextjs/dockerfile
    ports:
      - "3000:3000" 
    depends_on:
      - redis
      - postgres




