/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/133gb1ArJED
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function chatboxV0() {
  return (
    <div className="flex h-[800px] w-[800px] bg-background rounded-lg shadow-lg overflow-hidden">
      <div className="flex-1 overflow-auto p-6 space-y-6">
        <div className="flex items-start gap-4">
          <Avatar className="w-10 h-10 shrink-0">
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>JD</AvatarFallback>
          </Avatar>
          <div className="bg-muted rounded-lg p-4 max-w-[70%]">
            <div className="font-medium">John Doe</div>
            <div>Hey, how's it going?</div>
          </div>
        </div>
        <div className="flex items-start gap-4 justify-end">
          <div className="bg-primary rounded-lg p-4 max-w-[70%] text-primary-foreground">
            <div className="font-medium">Jane Smith</div>
            <div>I'm doing great, thanks for asking!</div>
          </div>
          <Avatar className="w-10 h-10 shrink-0">
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>JS</AvatarFallback>
          </Avatar>
        </div>
        <div className="flex items-start gap-4">
          <Avatar className="w-10 h-10 shrink-0">
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>JD</AvatarFallback>
          </Avatar>
          <div className="bg-muted rounded-lg p-4 max-w-[70%]">
            <div className="font-medium">John Doe</div>
            <img src="/placeholder.svg" width={600} height={400} alt="Image" className="rounded-lg my-2" />
          </div>
        </div>
        <div className="flex items-start gap-4 justify-end">
          <div className="bg-primary rounded-lg p-4 max-w-[70%] text-primary-foreground">
            <div className="font-medium">Jane Smith</div>
            <div>That's a great photo! I love the composition.</div>
          </div>
          <Avatar className="w-10 h-10 shrink-0">
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>JS</AvatarFallback>
          </Avatar>
        </div>
      </div>
      <div className="bg-background border-t border-muted flex items-center px-6 py-3 gap-3">
        <Textarea
          placeholder="Type your message..."
          className="flex-1 resize-none rounded-lg p-3 border border-muted focus:border-primary focus:ring-1 focus:ring-primary"
        />
        <Button variant="ghost" size="icon" className="rounded-full">
          <SendIcon className="w-6 h-6" />
          <span className="sr-only">Send</span>
        </Button>
      </div>
    </div>
  )
}

function SendIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
